baseURL = "/"
canonifyURLs = true
defaultContentLanguage = "ua"
disableLanguages = []
languageCode = "ua"
paginate = "6"
relativeURLs = true
summaryLength = "50"
title = "jo1n - Главная"
# [Languages.en]
# contentDir = "content/en"
# home = "Home"
# languageCode = "en-us"
# languageName = "En"
# weight = 3
[Languages.ru]
contentDir = "content/ru"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 2
[Languages.ua]
contentDir = "content/ua"
home = "Головна"
languageCode = "ua"
languageName = "Укр"
weight = 1
[[Languages.ua.footer.col]]
links = [["Оферта", "/offer/"], ["Політика обробки персональних даних", "/personal-data/"]]
title = "Юридична інформація"
[[Languages.ua.footer.col]]
links = [["ТОВ “МС ПЕЙ” \n Київ, вул. Солом'янська 3, оф. 6", "/"], ["join.commercial@gmail.com", "mailto:join.commercial@gmail.com"]]
title = "Контакти"
[[Languages.ua.modal.error]]
title = ""
title_sub = ""
[[Languages.ua.modal.send]]
title = ""
title_sub = ""
[[Languages.ua.modal.success]]
btn_label = "Ок"
btn_url = "#"
title = "Заявку успішно надіслано"
title_sub = "Упродовж одного робочого дня наш менеджер зв'яжеться з вами, щоб обговорити подальшу співпрацю."
[Languages.ua.params.form]
action = "#"
enable = true
method = "POST"
[[Languages.ua.params.form.field]]
enable = true
name = "name"
placeholder = "**\\*** Ім`я"
required = ""
type = "text"
# [[Languages.ua.params.form.field]]
# enable = true
# name = "email"
# placeholder = "* Email"
# required = ""
# type = "email"
[[Languages.ua.params.form.field]]
enable = true
name = "tel"
placeholder = "+38 (0__) ___ - __ - __"
label = "Телефон"
required = ""
type = "tel"
# [[Languages.ua.params.form.field]]
# enable = true
# name = "url"
# placeholder = "Сайт магазину"
# required = ""
# type = "url"
[[Languages.ua.params.form.field]]
enable = true
placeholder = "Надіслати"
type = "submit"
[[menu.footer]]
URL = "/affiliates/"
name = "Партнери"
weight = 5
[[menu.footer]]
URL = "/shop/"
name = "Магазинам"
weight = 4
[[menu.footer]]
URL = "/banks/"
name = "Банкам та МФО"
weight = 3
[[menu.footer]]
URL = "about/"
name = "Про нас"
weight = 2
[[menu.footer]]
URL = "/"
name = "Головна"
weight = 1
[[menu.header]]
URL = "/affiliates/"
name = "Партнери"
weight = 4
[[menu.header]]
URL = "/shop/"
name = "Магазинам"
weight = 3
[[menu.header]]
URL = "/banks/"
name = "Банкам і МФО"
weight = 2
[[menu.header]]
URL = "/about/"
name = "Про нас"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
CIO_site_id = "XXX"
GTM = "GTM-WHBQ3BV"
address = "ТОВ “МС ПЕЙ” \n Київ, вул. Солом'янська 3, оф. 6"
copy = "&copy; 2021 JO1N Ltd"
description = ""
develop = "xfr"
email = "join.commercial@gmail.com"
home = "Home"
logo = "/images/logo.svg"
logo_dark = "/images/logo_dark.svg"
logo_w = "101"
mobile = "(097) 875 12 43"
site_name = "Join1"
site_url = "join1.com"
tm_id = "-587397444"
tm_token = "2045157225:AAFQjtb_C69OrQqaXjNLnpODfFy01tIe1Lg"
[[params.plugins.css]]
link = "plugins/js/animate.min.css"
[[params.plugins.js]]
link = "plugins/js/wow.min.js"
[[params.plugins.js]]
link = "plugins/js/bootstrap.bundle.min.js"
[[params.plugins.js]]
link = "plugins/js/jquery.min.js"
[[params.plugins.js]]
link = "plugins/js/just-validate.min.js"
[[params.plugins.js]]
link = "plugins/js/smtp.js"
[params.preloader]
enable = true
preloader = ""
[sitemap]
ChangeFreq = "daily"
Priority = 0.6
Weight = [["main", "1"], ["sub2", "0.8"], ["sub3", "0.6"]]
enableRobotsTXT = true
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
