---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Партнери
- type: document
  path: content/en/affiliates/_index.md
  label: Партнери (EN)
- type: document
  path: content/ru/affiliates/_index.md
  label: Партнери (RU)
- type: document
  path: content/ua/affiliates/_index.md
  label: Партнери (UA)
- type: heading
  label: Політика
- type: document
  path: content/ua/policy/_index.md
  label: Політика (UA)
- type: document
  path: content/ru/policy/_index.md
  label: Політика (RU)
- type: document
  path: content/en/policy/_index.md
  label: Політика (EN)
- type: document
  path: content/ru/offer/_index.md
  label: Оферта (RU)
- type: document
  path: content/ua/offer/_index.md
  label: 'Оферта (UA)                                               '
- type: document
  path: content/en/offer/_index.md
  label: 'Оферта (EN)                                               '
- type: document
  path: content/en/shop/index.md
  label: Магазинам (EN)
- type: document
  path: content/ru/shop/index.md
  label: Магазинам (RU)
- type: document
  path: content/ua/shop/index.md
  label: Магазинам (UA)
- type: document
  path: content/en/banks/index.md
  label: Банкам і МФО (EN)
- type: document
  path: content/ru/banks/index.md
  label: Банкам і МФО (RU)
- type: document
  path: content/ua/banks/index.md
  label: Банкам і МФО (UA)
- type: document
  path: content/en/about/index.md
  label: Про нас (EN)
- type: document
  path: content/ru/about/index.md
  label: Про нас (RU)
- type: document
  path: content/ua/about/index.md
  label: Про нас (UA)
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
