---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Магазинам
- type: document
  path: content/en/shop
  label: Магазинам (EN)
- type: document
  path: content/ru/shop
  label: Магазинам (RU)
- type: document
  path: content/ua/shop
  label: Магазинам (UA)
- type: document
  path: content/en/banks
  label: Банкам і МФО (EN)
- type: document
  path: content/ru/banks
  label: Банкам і МФО (RU)
- type: document
  path: content/ua/banks
  label: Банкам і МФО (UA)
- type: heading
  label: Про нас
- type: document
  path: content/en/about
  label: Про нас (EN)
- type: document
  path: content/ru/about
  label: Про нас (RU)
- type: document
  path: content/ua/about
  label: Про нас (UA)
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
